### ISSUE TITLE
Docker?

### ISSUE THREAD

**Issue by SurvivaLlama** [ajnart/subs#5]
Can someone set up a docker for this?

**Comment by ajnart** [comment]
Can you try using an LLM, should be pretty straight forward, the page created from the build is static at the moment

**Comment by A-Specker** [comment]
@SurvivaLlama  there is an open PR https://github.com/bakudan-otaku/subs/tree/feature/docker

**Comment by SurvivaLlama** [comment]
You can close this. Someone made what I was looking for. https://github.com/nwithan8/unraid_templates
